### ISSUE TITLE
When I type the command python setup.py develop on linux, I get the following error:

### ISSUE THREAD

**Issue by Leekinxun** [KwaiKEG/KwaiAgents#12]
self.initialize_options()
aiohttp/_websocket.c: In function ‘__Pyx_ParseOptionalKeywords’:
aiohttp/_websocket.c:2166:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2166 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2166:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
 2166 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2166:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2166 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2166:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2166 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2166:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
 2166 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2166:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2166 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2182:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2182 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2182:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
 2182 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2182:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2182 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2182:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2182 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2182:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
 2182 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_websocket.c:2182:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
 2182 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_websocket.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_find_header.c: In function ‘find_header’:
aiohttp/_find_header.c:21:19: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   21 |     char *pchar = str;
      |                   ^~~
aiohttp/_find_header.c:9997:1: warning: label ‘missing’ defined but not used [-Wunused-label]
 9997 | missing:
      | ^~~~~~~
aiohttp/_find_header.c:27:1: warning: label ‘INITIAL’ defined but not used [-Wunused-label]
   27 | INITIAL:
      | ^~~~~~~
aiohttp/_http_parser.c: In function ‘__pyx_f_7aiohttp_12_http_parser_cb_on_header_field’:
aiohttp/_http_parser.c:11643:34: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
11643 |       __pyx_t_6 = ((__pyx_v_size > __pyx_v_pyparser->_max_field_size) != 0);
      |                                  ^
aiohttp/_http_parser.c:11739:148: warning: passing argument 2 of ‘__pyx_v_pyparser->__pyx_vtab->_on_header_field’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
11739 |       __pyx_t_1 = ((struct __pyx_vtabstruct_7aiohttp_12_http_parser_HttpParser *)__pyx_v_pyparser->__pyx_vtab)->_on_header_field(__pyx_v_pyparser, __pyx_v_at, __pyx_v_length); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 638, __pyx_L3_error)
      |                                                                                                                                                    ^~~~~~~~~~
aiohttp/_http_parser.c:11739:148: note: expected ‘char *’ but argument is of type ‘const char *’
aiohttp/_http_parser.c: In function ‘__pyx_f_7aiohttp_12_http_parser_cb_on_header_value’:
aiohttp/_http_parser.c:11961:34: warning: comparison of integer expressions of different signedness: ‘Py_ssize_t’ {aka ‘long int’} and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
11961 |       __pyx_t_6 = ((__pyx_v_size > __pyx_v_pyparser->_max_field_size) != 0);
      |                                  ^
aiohttp/_http_parser.c:12057:148: warning: passing argument 2 of ‘__pyx_v_pyparser->__pyx_vtab->_on_header_value’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
12057 |       __pyx_t_1 = ((struct __pyx_vtabstruct_7aiohttp_12_http_parser_HttpParser *)__pyx_v_pyparser->__pyx_vtab)->_on_header_value(__pyx_v_pyparser, __pyx_v_at, __pyx_v_length); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 655, __pyx_L3_error)
      |                                                                                                                                                    ^~~~~~~~~~
aiohttp/_http_parser.c:12057:148: note: expected ‘char *’ but argument is of type ‘const char *’
aiohttp/_http_parser.c: In function ‘__pyx_tp_dealloc_7aiohttp_12_http_parser_HttpParser’:
aiohttp/_http_parser.c:16227:5: error: lvalue required as increment operand
16227 |     ++Py_REFCNT(o);
      |     ^~
aiohttp/_http_parser.c:16229:5: error: lvalue required as decrement operand
16229 |     --Py_REFCNT(o);
      |     ^~
aiohttp/_http_parser.c: In function ‘__Pyx_decode_c_bytes’:
aiohttp/_http_parser.c:19932:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
19932 |         return PyUnicode_FromUnicode(NULL, 0);
      |         ^~~~~~
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:551:42: note: declared here
  551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
      |                                          ^~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c: In function ‘__Pyx_ParseOptionalKeywords’:
aiohttp/_http_parser.c:20030:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20030 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20030:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
20030 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20030:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20030 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20030:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20030 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20030:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
20030 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20030:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20030 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                     ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20046:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20046 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20046:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
20046 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20046:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20046 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20046:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20046 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20046:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
20046 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
  580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
      |                                             ^~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c:20046:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
20046 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
      |                         ^
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
  446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c: In function ‘__Pyx_decode_c_string’:
aiohttp/_http_parser.c:21230:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
21230 |         return PyUnicode_FromUnicode(NULL, 0);
      |         ^~~~~~
In file included from /data02/miniconda/envs/KwaiAgents/include/python3.10/unicodeobject.h:1046,
                 from /data02/miniconda/envs/KwaiAgents/include/python3.10/Python.h:83,
                 from aiohttp/_http_parser.c:4:
/data02/miniconda/envs/KwaiAgents/include/python3.10/cpython/unicodeobject.h:551:42: note: declared here
  551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
      |                                          ^~~~~~~~~~~~~~~~~~~~~
aiohttp/_http_parser.c: In function ‘__Pyx_Coroutine_Send’:
aiohttp/_http_parser.c:23271:19: warning: implicit declaration of function ‘_PyGen_Send’; did you mean ‘_PyGen_yf’? [-Wimplicit-function-declaration]
23271 |             ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
      |                   ^~~~~~~~~~~
      |                   _PyGen_yf
aiohttp/_http_parser.c:23271:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
23271 |             ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
      |                 ^
aiohttp/_http_parser.c:23276:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
23276 |             ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
      |                 ^
aiohttp/_http_parser.c: In function ‘__Pyx_Generator_Next’:
aiohttp/_http_parser.c:23360:17: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
23360 |             ret = _PyGen_Send((PyGenObject*)yf, NULL);
      |                 ^
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1

**Comment by ScarletPan** [comment]
Can you check aiohttp package by ``python -m pip show aiohttp`` or reinstall it ``pip install --upgrade aiohttp``?

**Comment by Leekinxun** [comment]
> Can you check aiohttp package by `python -m pip show aiohttp` or reinstall it `pip install --upgrade aiohttp`?

Thank you very much for your help！！
