### ISSUE TITLE
[build error]get error when i try pip install vllm

### ISSUE THREAD

**Issue by T-bagwell** [KwaiKEG/KwaiAgents#13]
`(base) liuqi-de-MacBook-Pro:KwaiAgents liuqi$ pip install -r requirements.txt
Collecting bs4 (from -r requirements.txt (line 1))
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting pandas (from -r requirements.txt (line 2))
  Downloading pandas-2.1.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (18 kB)
Collecting docstring_parser (from -r requirements.txt (line 3))
  Downloading docstring_parser-0.15-py3-none-any.whl (36 kB)
Collecting lunar_python==1.3.2 (from -r requirements.txt (line 4))
  Downloading lunar_python-1.3.2.tar.gz (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.7/103.7 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting duckduckgo-search==4.1.1 (from -r requirements.txt (line 5))
  Downloading duckduckgo_search-4.1.1-py3-none-any.whl.metadata (19 kB)
Collecting selenium==4.1.4 (from -r requirements.txt (line 6))
  Downloading selenium-4.1.4-py3-none-any.whl (979 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 979.3/979.3 kB 9.9 MB/s eta 0:00:00
Collecting webdriver-manager==3.8.6 (from -r requirements.txt (line 7))
  Downloading webdriver_manager-3.8.6-py2.py3-none-any.whl (27 kB)
Collecting openai==0.27.8 (from -r requirements.txt (line 8))
  Downloading openai-0.27.8-py3-none-any.whl.metadata (13 kB)
Collecting translate==3.6.1 (from -r requirements.txt (line 9))
  Downloading translate-3.6.1-py2.py3-none-any.whl (12 kB)
Collecting ephem==4.1.4 (from -r requirements.txt (line 10))
  Downloading ephem-4.1.4.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 26.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting click>=8.1.7 (from duckduckgo-search==4.1.1->-r requirements.txt (line 5))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting lxml>=4.9.3 (from duckduckgo-search==4.1.1->-r requirements.txt (line 5))
  Downloading lxml-5.0.0-cp311-cp311-macosx_11_0_universal2.whl.metadata (6.7 kB)
Collecting curl-cffi>=0.5.10 (from duckduckgo-search==4.1.1->-r requirements.txt (line 5))
  Downloading curl_cffi-0.5.10-cp37-abi3-macosx_11_0_arm64.whl.metadata (7.9 kB)
Requirement already satisfied: urllib3~=1.26 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from urllib3[secure,socks]~=1.26->selenium==4.1.4->-r requirements.txt (line 6)) (1.26.18)
Collecting trio~=0.17 (from selenium==4.1.4->-r requirements.txt (line 6))
  Downloading trio-0.23.2-py3-none-any.whl.metadata (4.9 kB)
Collecting trio-websocket~=0.9 (from selenium==4.1.4->-r requirements.txt (line 6))
  Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: requests in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from webdriver-manager==3.8.6->-r requirements.txt (line 7)) (2.31.0)
Collecting python-dotenv (from webdriver-manager==3.8.6->-r requirements.txt (line 7))
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Requirement already satisfied: tqdm in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from webdriver-manager==3.8.6->-r requirements.txt (line 7)) (4.65.0)
Requirement already satisfied: packaging in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from webdriver-manager==3.8.6->-r requirements.txt (line 7)) (23.1)
Collecting aiohttp (from openai==0.27.8->-r requirements.txt (line 8))
  Downloading aiohttp-3.9.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting libretranslatepy==2.1.1 (from translate==3.6.1->-r requirements.txt (line 9))
  Downloading libretranslatepy-2.1.1-py3-none-any.whl (3.2 kB)
Collecting beautifulsoup4 (from bs4->-r requirements.txt (line 1))
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 kB 18.6 MB/s eta 0:00:00
Collecting numpy<2,>=1.23.2 (from pandas->-r requirements.txt (line 2))
  Downloading numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB 14.0 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2 (from pandas->-r requirements.txt (line 2))
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 27.5 MB/s eta 0:00:00
Collecting pytz>=2020.1 (from pandas->-r requirements.txt (line 2))
  Downloading pytz-2023.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.1 (from pandas->-r requirements.txt (line 2))
  Downloading tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: cffi>=1.12.0 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from curl-cffi>=0.5.10->duckduckgo-search==4.1.1->-r requirements.txt (line 5)) (1.16.0)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2))
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from requests->webdriver-manager==3.8.6->-r requirements.txt (line 7)) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from requests->webdriver-manager==3.8.6->-r requirements.txt (line 7)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from requests->webdriver-manager==3.8.6->-r requirements.txt (line 7)) (2023.11.17)
Collecting attrs>=20.1.0 (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting sortedcontainers (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio~=0.17->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pyOpenSSL>=0.14 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from urllib3[secure,socks]~=1.26->selenium==4.1.4->-r requirements.txt (line 6)) (23.2.0)
Requirement already satisfied: cryptography>=1.3.4 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from urllib3[secure,socks]~=1.26->selenium==4.1.4->-r requirements.txt (line 6)) (41.0.7)
Collecting urllib3-secure-extra (from urllib3[secure,socks]~=1.26->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading urllib3_secure_extra-0.1.0-py2.py3-none-any.whl (1.4 kB)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from urllib3[secure,socks]~=1.26->selenium==4.1.4->-r requirements.txt (line 6)) (1.7.1)
Collecting multidict<7.0,>=4.5 (from aiohttp->openai==0.27.8->-r requirements.txt (line 8))
  Downloading multidict-6.0.4-cp311-cp311-macosx_11_0_arm64.whl (29 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->openai==0.27.8->-r requirements.txt (line 8))
  Downloading yarl-1.9.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (31 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->openai==0.27.8->-r requirements.txt (line 8))
  Downloading frozenlist-1.4.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->openai==0.27.8->-r requirements.txt (line 8))
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting soupsieve>1.2 (from beautifulsoup4->bs4->-r requirements.txt (line 1))
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: pycparser in /Users/liuqi/miniconda3/lib/python3.11/site-packages (from cffi>=1.12.0->curl-cffi>=0.5.10->duckduckgo-search==4.1.1->-r requirements.txt (line 5)) (2.21)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium==4.1.4->-r requirements.txt (line 6))
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 9.6 MB/s eta 0:00:00
Downloading duckduckgo_search-4.1.1-py3-none-any.whl (26 kB)
Downloading openai-0.27.8-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 kB 8.4 MB/s eta 0:00:00
Downloading pandas-2.1.4-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 1.3 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 1.9 MB/s eta 0:00:00
Downloading curl_cffi-0.5.10-cp37-abi3-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.2 MB/s eta 0:00:00
Downloading lxml-5.0.0-cp311-cp311-macosx_11_0_universal2.whl (8.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 1.2 MB/s eta 0:00:00
Downloading numpy-1.26.3-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 1.2 MB/s eta 0:00:00
Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.5/502.5 kB 1.4 MB/s eta 0:00:00
Downloading trio-0.23.2-py3-none-any.whl (461 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.6/461.6 kB 1.3 MB/s eta 0:00:00
Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 1.5 MB/s eta 0:00:00
Downloading aiohttp-3.9.1-cp311-cp311-macosx_11_0_arm64.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.8/386.8 kB 1.3 MB/s eta 0:00:00
Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 1.1 MB/s eta 0:00:00
Downloading frozenlist-1.4.1-cp311-cp311-macosx_11_0_arm64.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.4/53.4 kB 897.8 kB/s eta 0:00:00
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Downloading yarl-1.9.4-cp311-cp311-macosx_11_0_arm64.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 1.5 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: lunar_python, ephem, bs4
  Building wheel for lunar_python (setup.py) ... done
  Created wheel for lunar_python: filename=lunar_python-1.3.2-py3-none-any.whl size=113790 sha256=1dbcb26512c9c700eb995a0c9d13685eafc0cf6b3e9f26ab5426b1aac60ac2d8
  Stored in directory: /Users/liuqi/Library/Caches/pip/wheels/6a/73/58/1b80d8b1e096d6e501e68af3b0b06d0853d174fe1840a93161
  Building wheel for ephem (setup.py) ... done
  Created wheel for ephem: filename=ephem-4.1.4-cp311-cp311-macosx_11_0_arm64.whl size=1421773 sha256=825829c986be5b9020a8087634c6c6b39ae11920ed93d6406d2e69872b12ae98
  Stored in directory: /Users/liuqi/Library/Caches/pip/wheels/c8/40/d4/dda0a71c5a493dafbcc1f1a5dca07363f6ff2d12046879f109
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1256 sha256=412e0f58edaf7553bc201a656ffaa1046b1227b7ef04ff6686e10048933cdcaa
  Stored in directory: /Users/liuqi/Library/Caches/pip/wheels/d4/c8/5b/b5be9c20e5e4503d04a6eac8a3cd5c2393505c29f02bea0960
Successfully built lunar_python ephem bs4
Installing collected packages: urllib3-secure-extra, sortedcontainers, pytz, lunar_python, libretranslatepy, ephem, tzdata, soupsieve, sniffio, six, python-dotenv, numpy, multidict, lxml, h11, frozenlist, docstring_parser, click, attrs, yarl, wsproto, webdriver-manager, translate, python-dateutil, outcome, curl-cffi, beautifulsoup4, aiosignal, trio, pandas, duckduckgo-search, bs4, aiohttp, trio-websocket, openai, selenium
Successfully installed aiohttp-3.9.1 aiosignal-1.3.1 attrs-23.2.0 beautifulsoup4-4.12.2 bs4-0.0.1 click-8.1.7 curl-cffi-0.5.10 docstring_parser-0.15 duckduckgo-search-4.1.1 ephem-4.1.4 frozenlist-1.4.1 h11-0.14.0 libretranslatepy-2.1.1 lunar_python-1.3.2 lxml-5.0.0 multidict-6.0.4 numpy-1.26.3 openai-0.27.8 outcome-1.3.0.post0 pandas-2.1.4 python-dateutil-2.8.2 python-dotenv-1.0.0 pytz-2023.3.post1 selenium-4.1.4 six-1.16.0 sniffio-1.3.0 sortedcontainers-2.4.0 soupsieve-2.5 translate-3.6.1 trio-0.23.2 trio-websocket-0.11.1 tzdata-2023.4 urllib3-secure-extra-0.1.0 webdriver-manager-3.8.6 wsproto-1.2.0 yarl-1.9.4
(base) liuqi-de-MacBook-Pro:KwaiAgents liuqi$ pip install vllm
Collecting vllm
  Downloading vllm-0.2.7.tar.gz (170 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.8/170.8 kB 866.3 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      /private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      Traceback (most recent call last):
        File "/Users/liuqi/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/liuqi/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/liuqi/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 230, in <module>
        File "/private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1203, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/j9/6yjlhjjd3gvgb8xsw4jl0vb40000gp/T/pip-build-env-nmd98nig/overlay/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(base) liuqi-de-MacBook-Pro:KwaiAgents liuqi$`

**Comment by T-bagwell** [comment]
`CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

Do not support start on macbook?

**Comment by ScarletPan** [comment]
It seems like that, we are considering to incorporate `llama.cpp` and small llms to run on CPU.

**Comment by ScarletPan** [comment]
support CPU by this commit [925e786](https://github.com/KwaiKEG/KwaiAgents/commit/925e78645aa1e10ece9885dc5738ff47e01b1582)
