### ISSUE TITLE
Training with publish kwaiAgentInstruct dataset

### ISSUE THREAD

**Issue by superobk** [KwaiKEG/KwaiAgents#14]
Hello, may we have the training/finetune code with kwaiAgentInstruct, specially finetu ne for Qwen. Thank you!

**Comment by Beckham007** [comment]
+1

**Comment by zzp-seeker** [comment]
You can refer to the finetuning instructions available at https://github.com/QwenLM/Qwen/tree/main?tab=readme-ov-file#finetuning. For our full parameter finetuning, we utilize a DeepSpeed + Zero3 configuration. You can find the DeepSpeed configuration details here: https://github.com/QwenLM/Qwen/blob/main/finetune/ds_config_zero3.json. For more training specifics, refer to our [paper](https://arxiv.org/pdf/2312.04889.pdf.). Please note that during training, along with the Agent-type data we provide, you should independently incorporate General-type data into the training set.
