### ISSUE TITLE
Questions enquiry for KwaiAgentSys and MAT model 

### ISSUE THREAD

**Issue by superobk** [KwaiKEG/KwaiAgents#19]
Hello, here are some questions and want to understand. Please kindly assist.
1.
May I know how to use kagentsys in conversation mode? Currently with default parameters in README, it can only have one question for prompt input with 5 iterations maximum.
2.
For MAT model of Baichuan2 published, the base training model is [Baichuan2-13B-Chat] or [Baichuan2-13B-Base]? If MAT finetuning is based on [Baichuan2-13B-Base], could we have some way to finetune well in [Baichuan2-13B-Chat]?
3.
Did MAT models tested in other Agents framework, such as LangChain or AutoGPT? If yes, how is the performance.

Thank you in advance!

**Comment by ScarletPan** [comment]
Hi, thanks for your questions.
1. You can directly use `AgentService` class in `kwaiagents/agent_start.py` and pass `history` to activate conversation mode. We will give a tutorial soon in README.md
2. The Baichuan2-13B-Chat is used as the base model.
3. Yes, you can check the benchmark results both in README and our papers. In Langchain, actually they use ReAct prompt templates.

**Comment by superobk** [comment]
> Hi, thanks for your questions.
> 
> 1. You can directly use `AgentService` class in `kwaiagents/agent_start.py` and pass `history` to activate conversation mode. We will give a tutorial soon in README.md
> 2. The Baichuan2-13B-Chat is used as the base model.
> 3. Yes, you can check the benchmark results both in README and our papers. In Langchain, actually they use ReAct prompt templates.

Thanks a lot, I will close the case.
