### ISSUE TITLE
Where can find the test data?

### ISSUE THREAD

**Issue by Vincent-Li-9701** [KwaiKEG/KwaiAgents#2]
Really interesting work! I wonder where can we find the test data? ./benchmark_eval.jsonl Interesting on query set used to test out this setup. Also, did we consider/compare against Google's rich answer system? Such as its snippet answer?

**Comment by ScarletPan** [comment]
1. The benchmark data and tutorial can be found in huggingface https://huggingface.co/datasets/kwaikeg/KAgentBench
2. Are you interested in contributing to this project and compare Google's rich answer system?
