### ISSUE TITLE
训练集(KAgentInstruct)数据问题

### ISSUE THREAD

**Issue by Emperorizzis** [KwaiKEG/KwaiAgents#20]
Hi, 感谢您针对“[训练集(KAgentlnstruct)ReACT数据问题](https://github.com/KwaiKEG/KwaiAgents/issues/18)”进行解决并更新了数据集，但我仍发现数据中存在下述现象与问题：

**1）训练集中“toolllama”存在较多相似数据 (相似数据会降低数据多样性，影响模型能力？)**
这类相似数据的input非常类似，且答案一般如下：
`\nThought: \nAction: top_memes_for_reddit_meme\nAction Input: {}`

**2）数据的response中存在语言不一致情况 (这种问题可能会造成模型选择回复语言混乱？)**
例如数据中，提问使用的是中文，在response中，思考等使用的是英文，回复使用的是中文

**3）训练集中react的prompt input部分不应包含“Thought”、"Final Answer"等组件名称，这些组件名称应放到response中训练**
由于react需学习思考、动作、观察与结果的时机，且在实际使用时也由模型生成，故这些组件名称应放到response中训练

**期待更新版训练数据的更新，再次感谢您的开源！**

**Comment by zzp-seeker** [comment]
感谢你的发现，我们已上传新的数据集
