### ISSUE TITLE
hello,How to customize a tool and invoke it, similar to langchain? Or directly use langchain.

### ISSUE THREAD

**Issue by dgo2dance** [KwaiKEG/KwaiAgents#26]
hello,How to customize a tool and invoke it, similar to langchain? Or directly use langchain.

**Comment by HarryYuan007** [comment]
You can create a new custom tool in the kwaiagents/tools directory. Refer to the code in base.py and other tools, and inherit the implementations of BaseToo and BaseResultl to build your own tool. When used, kwaiagents will automatically include it in the prompts for the Agent to select!

**Comment by ScarletPan** [comment]
Hi, thanks for your concerns. Here we just add a custom tool-use example: https://github.com/KwaiKEG/KwaiAgents/blob/main/examples/custom_tool_example.py
