### ISSUE TITLE
Results of KAgentSys-Lite on KAgentBench

### ISSUE THREAD

**Issue by sbl1996** [KwaiKEG/KwaiAgents#3]
Thanks for your great work! It appears that the open-sourced KAgentSys-Lite may have limitations compared to the more powerful tools used in KAgentSys as described in the paper. As a result, it is crucial to understand what the experimental results of KAgentSys-Lite would be on KAgentBench, similar to the results presented in Table 3 of the paper. This information holds significant importance for the users of KAgentSys-Lite.

**Comment by ScarletPan** [comment]
Hello, and thank you for your insightful observations. Please be assured that KAgentSys-Lite, being a system-level alteration (with the same prompt templates), will not affect the model's capability as shown in Table 3. Furthermore, in Section "4.4 Ablation Study", we provide the results as a supplement of Table 4 relating to the performance of KAgentSys-Lite. These results can be referenced by users to gauge the potential performance reduction in the lite version
