### ISSUE TITLE
Concluding 和 Profile 指标有什么不同？

### ISSUE THREAD

**Issue by ljch2018** [KwaiKEG/KwaiAgents#31]
![image](https://github.com/KwaiKEG/KwaiAgents/assets/22562546/720c7583-2765-4666-a757-4e24233a4a38)
从源代码上看，这两个指标作用是一样的。感谢。

**Comment by HarryYuan007** [comment]
您好，这两个指标都是计算了infer和ground truth的ROUGE值，计算方式是相同的，略有不同的是conclusion有不同的prompt模版（M个），profile只有一个prompt模版但是有5个答案，所以公式上稍有不同，conclusion会在使用不同prompt模版后预测的结果计算的分数上做个mean操作（1/M），profile的计算公式则没有。
希望能解答您的疑惑。
