### ISSUE TITLE
两个关于KAgentInstruct数据集的问题

### ISSUE THREAD

**Issue by xyfZzz** [KwaiKEG/KwaiAgents#33]
请问下两个关于KAgentInstruct数据集的问题：
1、source为kwai-agent和kwaiagent的两部分数据有什么区别？
2、每行数据中的"llm_prompt_response"字段是个list，"llm_prompt_response"字段下的各个dict（每个dict中有“input”、“instruction”、“output”）在训练时需要合并到一个conversation中吗？（或者说"llm_prompt_response"字段下的各个dict是否独立且不需要考虑加入上下文）

感谢！

**Comment by zzp-seeker** [comment]
1、source为kwai-agent和kwaiagent是一致的，不过KAgentInstruct只有kwai-agent吧
2、不需要合并
