### ISSUE TITLE
Can the KAgentInstruct dataset be open sourced or used as a reference

### ISSUE THREAD

**Issue by maqiang515** [KwaiKEG/KwaiAgents#4]
Can the KAgentInstruct dataset be open sourced or used as a reference;Thank you.

**Comment by ScarletPan** [comment]
Certainly! We're targeting to open-source the KAgentInstruct dataset, or make it available for reference use by the beginning of January 2024. We're currently attending to some procedural matters, but we'll keep you updated on our progress. Thank you for your interest

**Comment by maqiang515** [comment]
Thank you very much

**Comment by zzp-seeker** [comment]
@maqiang515 https://huggingface.co/datasets/kwaikeg/KAgentInstruct
