### ISSUE TITLE
几个任务的解释

### ISSUE THREAD

**Issue by abc123456cxx** [KwaiKEG/KwaiAgents#40]
有几个没太明白想请问一下， 这几个任务：plan, tools, reflection, conclusion, profile分别是测试模型的什么方面呢（看数据集和论文没太理解），这几个任务都需要联网调用api吗，如果机器不能联网可以测试哪些任务呢，感谢解答🙏

**Comment by HarryYuan007** [comment]
您好，planing是测试模型在任务规划的能力；tools是评测模型在调用工具以及生成具体工具调用参数的能力；reflection是评测模型的反思能力；conclusion是评测模型的整合信息总结归纳能力；profile是评测模型在人设扮演上的能力。
如果您只是想评估agent的能力，只需要使用模型跑我们的benchmark即可，不涉及到联网问题。但是如果想跑起来demo，那是需要来联网实现对一些工具的调用，或则您也可以修改工具为本地的一些工具调用，则无需联网。
