### ISSUE TITLE
Expecting the KAgentInstruct TrainingData and Training Guide

### ISSUE THREAD

**Issue by xiesiyang** [KwaiKEG/KwaiAgents#7]
非常有启发性的项目，我从中学到很多知识。
希望尽快深入了解有关模型训练的细节及数据，非常感谢！

**Comment by ScarletPan** [comment]
感谢你的关注，正在准备中

**Comment by Nipi64310** [comment]
哈喽，@ScarletPan 感谢开源 ！
mark ，数据更新通知一下，有预计时间吗？ 会烂尾吗？

**Comment by ScarletPan** [comment]
预计这两周会开源，感谢关注！

**Comment by zzp-seeker** [comment]
训练数据已经上传：https://huggingface.co/datasets/kwaikeg/KAgentInstruct
